/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;

@Command(name = "xsaw", mixinStandardHelpOptions = true, version = "1.0.0",
        description = "Lists files in the current directory.",
        subcommands = {App.LsCommand.class})

public class App implements Callable<Integer> {
    @Override
    public Integer call() {
        CommandLine.usage(this, System.out);
        return 0;
    }

    @Command (name = "ls", description = "Lists files in the current directory.")
    static class LsCommand implements Callable<Integer> {
        @Parameters (index = "0", description = "The directory to list files from.", defaultValue = ".")
        private Path targetDir;

        @Override
        public Integer call() {
            Path path = targetDir.toAbsolutePath().normalize();

            if (!Files.isDirectory(path)) {
                System.err.println("Error: " + path + " is not a directory.");
                return 1;
            }

            try {
                ls ls = new ls();
                FileResult result = ls.analyze(path);
                System.out.printf("Directory: %s%n%n", result.rootDir());
                System.out.printf("%-14s %,10d%n", "Files:", result.fileCount());
                System.out.printf("%-14s %,10d%n", "Directories:", result.dirCount());
                System.out.printf("%-14s %10s%n%n", "Total size:", result.formattedTotalSize());
                System.out.println("Extension statistics:");
                System.out.println();

                long totalFiles = result.fileCount();
                if (totalFiles > 0) {
                    var sortedList = result.extensions().entrySet().stream()
                        .sorted((a, b) -> Long.compare(b.getValue().count(), a.getValue().count()))
                        .toList();
                    
                    int topCount = Math.min(4, sortedList.size());
                    long topFilesSum = 0;
                    for (int i = 0; i < topCount; i++) {
                        var entry = sortedList.get(i);
                        double percentage = (double) entry.getValue().count() / totalFiles * 100;
                        System.out.printf("%-10s %5.1f%%%n", entry.getKey(), percentage);
                        topFilesSum += entry.getValue().count();
                    }

                    long otherFilesCount = totalFiles - topFilesSum;
                    if (otherFilesCount > 0) {
                        double otherPercentage = (double) otherFilesCount / totalFiles * 100;
                        System.out.printf("%-10s %5.1f%%%n", "Other", otherPercentage);
                    }
                }
                return 0;
            } catch (IOException e) {
                System.err.println("Error analyzing directory: " + e.getMessage());
                return 1;
            }
        }
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }
}
