/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;

@Command(name = "xsaw", mixinStandardHelpOptions = true, version = "1.0.0",
        description = "Lists files in the current directory.",
        subcommands = {App.LsCommand.class})

public class App implements Callable<Integer> {
    @Override
    public Integer call() {
        CommandLine.usage(this, System.out);
        return 0;
    }

    @Command (name = "ls", description = "Lists files in the current directory.")
    static class LsCommand implements Callable<Integer> {
        @Parameters (index = "0", description = "The directory to list files from.", defaultValue = ".")
        private Path targetDir;

        @Override
        public Integer call() {
            Path path = targetDir.toAbsolutePath().normalize();

            if (!Files.isDirectory(path)) {
                System.err.println("Error: " + path + " is not a directory.");
                return 1;
            }

            System.out.println("Listing files in directory: " + path);
            // todo: Implement file listing logic here, e.g., using Files.list(path) and printing the file names.
            return 0;
        }
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }
}
