/*
 * This source file was generated by the Gradle 'init' task
 */
package cli;

import java.io.IOException;
import java.io.BufferedReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.Callable;
import java.util.List;
import java.util.ArrayList;

import du.*;
import fi.*;
import mv.*;
import gr.*;
import rm.*;
import history.*;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@Command(name = "xsaw", mixinStandardHelpOptions = true, version = "1.0.0",
        description = "Lists files in the current directory.",
        subcommands = {App.DuCommand.class, App.FiCommand.class, App.MvCommand.class, App.GrepCommand.class, App.RmCommand.class, App.LogCommand.class, App.PurgeCommand.class})

public class App implements Callable<Integer> {
    @Override
    public Integer call() {
        CommandLine.usage(this, System.out);
        return 0;
    }

    private static java.util.Set<String> normalizeExts(java.util.List<String> exts) {
        if (exts == null || exts.isEmpty()) return java.util.Set.of();
        return exts.stream()
            .filter(java.util.Objects::nonNull)
            .map(s -> s.trim())
            .filter(s -> !s.isEmpty())
            .map(s -> s.startsWith(".") ? s.substring(1).toLowerCase() : s.toLowerCase())
            .collect(java.util.stream.Collectors.toSet());
    }

    private static java.util.Set<String> normalizeDirs(java.util.List<String> dirs) {
        if (dirs == null || dirs.isEmpty()) return java.util.Set.of();
        return dirs.stream()
            .filter(java.util.Objects::nonNull)
            .map(String::trim)
            .filter(s -> !s.isEmpty())
            .collect(java.util.stream.Collectors.toSet());
    }

    private static boolean hasPipedInput() {
        try {
            return System.in.available() > 0;
        } catch (IOException e) {
            return false;
        }
    }

    @Command (name = "du", aliases = {"d"}, description = "Displays the number of files, directories, and total size of a specified directory, along with statistics on file extensions.")
    static class DuCommand implements Callable<Integer> {
        @Parameters (index = "0", description = "The directory to list files from, or '-' for standard input.", defaultValue = "")
        private String targetInput;

        @Option (names = {"-n", "--topN"}, description = "Number of top file extensions to display.(0 = all)", defaultValue = "4")
        private int topN;

        @Option (names = {"-l", "--list-only"}, description = "List only the file extensions without statistics.", defaultValue = "false")
        private boolean listOnly;

        @Option (names = {"-e", "--ext"}, split = ",", description = "Filter by file extensions (comma-separated or multiple flags).")
        private java.util.List<String> exts;

        @Option (names = {"-x", "--exclude"}, split = ",", description = "Exclude directories by name (comma-separated or multiple flags).")
        private java.util.List<String> excludeDirs;

        @Option (names = {"-h", "-H", "--hidden"}, description = "Include hidden files and directories (default: excluded).", defaultValue = "false")
        private boolean hidden;

        @Option (names = {"--help"}, usageHelp = true, description = "Display this help message.")
        private boolean helpRequested;

        @Override
        public Integer call() {
            if (helpRequested || "?".equals(targetInput) || "/?".equals(targetInput) || "help".equalsIgnoreCase(targetInput)) {
                CommandLine.usage(this, System.out);
                return 0;
            }

            boolean isExplicitStdin = "-".equals(targetInput);
            boolean isPiped = (targetInput.isEmpty() || ".".equals(targetInput)) && System.console() == null && hasPipedInput();

            try {
                du du = new du();
                FileResult result;
                var filterExts = normalizeExts(exts);
                var filterExcludeDirs = normalizeDirs(excludeDirs);

                if (isPiped || isExplicitStdin) {
                    var paths = new java.util.ArrayList<Path>();
                    try (var reader = new java.io.BufferedReader(new java.io.InputStreamReader(System.in, java.nio.charset.StandardCharsets.UTF_8))) {
                        String line;
                        while ((line = reader.readLine()) != null) {
                            String trimmed = line.trim();
                            if (!trimmed.isEmpty()) {
                                try {
                                    Path p = Path.of(trimmed);
                                    if (Files.exists(p)) {
                                        paths.add(p.toAbsolutePath().normalize());
                                    }
                                } catch (java.nio.file.InvalidPathException ignored) {}
                            }
                        }
                    }
                    result = du.analyze(paths, Path.of("(standard input)"), filterExts);
                } else {
                    Path path;
                    try {
                        path = Path.of(targetInput.isEmpty() ? "." : targetInput).toAbsolutePath().normalize();
                    } catch (java.nio.file.InvalidPathException e) {
                        System.err.println("Error: Invalid path '" + targetInput + "': " + e.getReason());
                        return 1;
                    }
                    if (!Files.isDirectory(path)) {
                        System.err.println("Error: " + path + " is not a directory.");
                        return 1;
                    }
                    result = du.analyze(path, filterExts, filterExcludeDirs, hidden);
                }

                System.out.printf("Directory: %s%n%n", result.rootDir());
                System.out.printf("%-14s %,10d%n", "Files:", result.fileCount());
                System.out.printf("%-14s %,10d%n", "Directories:", result.dirCount());
                System.out.printf("%-14s %10s%n%n", "Total size:", result.formattedTotalSize());
                System.out.printf("%-14s %10s%n%n", "Elapsed:", result.formattedElapsed());
                
                
                long totalFiles = result.fileCount();
                System.out.println();
                if (totalFiles > 0) {
                    var sortedList = result.extensions().entrySet().stream()
                        .filter(e -> !e.getKey().equals("other") && !e.getKey().equals("(none)") && !e.getKey().isEmpty())
                        .sorted((a, b) -> Long.compare(b.getValue().count(), a.getValue().count()))
                        .toList();
                    
                    int topCount = topN == 0 ? sortedList.size() : Math.min(topN, sortedList.size());
                    long topFilesSum = 0;
                    if (listOnly) {
                        System.out.println("extensions:");
                        int columns = 4;

                        for (int i = 0; i < topCount; i++) {
                            String ext = "." + sortedList.get(i).getKey();
                            System.out.printf("%-12s", ext);
                            if ((i + 1) % columns == 0 || i == topCount - 1) {
                                System.out.println();
                            }
                        }
                    } else {
                        System.out.println("Extension statistics:");
                        System.out.println();
                        for (int i = 0; i < topCount; i++) {
                            var entry = sortedList.get(i);
                            double percentage = (double) entry.getValue().count() / totalFiles * 100;
                            System.out.printf("%-10s %5.1f%%%n", entry.getKey(), percentage);
                            topFilesSum += entry.getValue().count();
                        }

                        long remainingFilesCount = totalFiles - topFilesSum;
                        if (topN > 0 && remainingFilesCount > 0) {
                            double otherPercentage = (double) remainingFilesCount / totalFiles * 100;
                            System.out.printf("%-10s %5.1f%%%n", "Other", otherPercentage);
                        }
                    }
                }
                return 0;
            } catch (IOException e) {
                System.err.println("Error analyzing directory: " + e.getMessage());
                return 1;
            }
        }
    }

    @Command (name = "fi", aliases = {"f"}, description = "Searches for files and directories matching a specified query within a given directory.")
    static class FiCommand implements Callable<Integer> {
        @Parameters (index = "0", description = "The search query (keyword).", defaultValue = "", arity = "0..1")
        private String query = "";

        @Parameters (index = "1", description = "The directory to search in.", defaultValue = ".", arity = "0..1")
        private Path targetDir;

        @Option (names = {"-s", "--case-sensitive"}, description = "Perform a case-sensitive search.", defaultValue = "false")
        private boolean caseSensitive;

        @Option (names = {"-d", "--dir-only"}, description = "Search for directories only.", defaultValue = "false")
        private boolean dirOnly;

        @Option (names = {"-f", "--file-only"}, description = "Search for files only.", defaultValue = "false")
        private boolean fileOnly;

        @Option (names = {"-e", "--ext"}, split = ",", description = "Filter results by file extensions (comma-separated or multiple flags).")
        private java.util.List<String> exts;

        @Option (names = {"-r", "--regex"}, description = "Treat the query as a regular expression.", defaultValue = "false")
        private boolean regex;

        @Option (names = {"-x", "--exclude"}, split = ",", description = "Exclude directories by name (comma-separated or multiple flags).")
        private java.util.List<String> excludeDirs;

        @Option (names = {"-h", "-H", "--hidden"}, description = "Include hidden files and directories (default: excluded).", defaultValue = "false")
        private boolean hidden;

        @Option (names = {"--help"}, usageHelp = true, description = "Display this help message.")
        private boolean helpRequested;

        @Override 
        public Integer call() {
            if (helpRequested || "?".equals(query) || "/?".equals(query) || "help".equalsIgnoreCase(query)) {
                CommandLine.usage(this, System.out);
                return 0;
            }

            if (targetDir == null) {
                targetDir = Path.of(".");
            }

            // もし `xsaw f . -e java` のように "." が query として渡された場合は検索ルートとみなす
            if (".".equals(query) || "./".equals(query) || ".\\".equals(query)) {
                targetDir = Path.of(query);
                query = "";
            }

            Path root = targetDir.toAbsolutePath().normalize();

            if (!Files.isDirectory(root)) {
                System.err.println("Error: " + root + " is not a directory.");
                return 1;
            }

            if (dirOnly && fileOnly) {
                System.err.println("Error: Cannot specify both --dir-only and --file-only options.");
                return 1;
            }

            try {
                fi finder = new fi();
                fi.FindOptions options = new fi.FindOptions(caseSensitive, dirOnly, fileOnly, regex, normalizeExts(exts), normalizeDirs(excludeDirs), hidden);
                FindResult result = finder.find(root, query, options);

                for (Path relativeMatch : result.relativeMatches()) {
                    System.out.println(relativeMatch);
                }

                System.err.println();
                System.err.printf("Found %d matches in %d ms.%n", result.count(), result.elapsedMillis());
                return 0;
            } catch (java.util.regex.PatternSyntaxException e) {
                System.err.println("Invalid regular expression: " + e.getDescription());
                return 1;
            } catch (IOException e) {
                System.err.println("Error searching directory: " + e.getMessage());
                return 1;
            }
        }
    }

    @Command (name = "mv", aliases = {"m"}, mixinStandardHelpOptions = true, description = "Moves a file or directory to a new location.")
    static class MvCommand implements Callable<Integer> {
        @Parameters (description = "The source file or directory to move.", arity = "0..*")
        private java.util.List<String> sourceRaw;

        @Option (names = {"-d", "--dry-run"}, description = "Perform a trial run without making any changes.", defaultValue = "false")
        private boolean dryRun;

        @Option (names = {"-f", "--force"}, description = "Force overwrite of existing files.", defaultValue = "false")
        private boolean force;

        @Option (names = {"-n", "--no-clobber"}, description = "Do not overwrite existing files.", defaultValue = "false")
        private boolean noClobber;

        @Option (names = {"-v", "--verbose"}, description = "Enable verbose output.", defaultValue = "false")
        private boolean verbose;

        @Override
        public Integer call() {
            if (sourceRaw == null || sourceRaw.isEmpty() || "?".equals(sourceRaw.get(0)) || "/?".equals(sourceRaw.get(0)) || "help".equalsIgnoreCase(sourceRaw.get(0))) {
                CommandLine.usage(this, System.out);
                return 0;
            }

            if (sourceRaw.size() < 2) {
                System.err.println("Error: Source and destination paths are required.");
                return 1;
            }

            if (force && noClobber) {
                System.err.println("Error: Cannot specify both --force and --no-clobber options.");
                return 1;
            }

            MoveOptions options = new MoveOptions(dryRun, force, noClobber, verbose);

            try {
                mv mover = new mv();
                String targetPathStr = sourceRaw.get(sourceRaw.size() - 1);
                Path destination = Path.of(targetPathStr);

                boolean isDirTarget = targetPathStr.endsWith("/") || targetPathStr.endsWith("\\") || Files.isDirectory(destination);
                if (sourceRaw.size() > 2 && !isDirTarget) {
                    System.err.println("Error: When moving multiple sources, the target must be a directory.");
                    return 1;
                }

                List<Path> sources = new ArrayList<>();
                for (int i = 0; i < sourceRaw.size() -1; i++) {
                    sources.add(Path.of(sourceRaw.get(i)));
                }

                List<MoveResult> results = new ArrayList<>();
                BufferedReader reader = new BufferedReader(new java.io.InputStreamReader(System.in, java.nio.charset.StandardCharsets.UTF_8));
                for (Path src : sources) {
                    Path finalDest = isDirTarget ? destination.resolve(src.getFileName()) : destination;

                    if (Files.exists(finalDest) && !force && !noClobber && !dryRun) {
                        ConflictAction action = promptConflictAction(src, finalDest, reader); 
                        switch (action) {
                            case OVERWRITE -> {
                                MoveOptions overwriteOpts = new MoveOptions(dryRun, true, false, verbose);
                                results.add(mover.move(src, finalDest, overwriteOpts));
                            }
                            case RENAME -> {
                                Path uniqueDest = mv.generateUniquePath(finalDest);
                                MoveResult res = mover.move(src, uniqueDest, options);
                                results.add(new MoveResult(res.source(), res.destination(), res.sizeBytes(), res.timestamp(), res.isDirectory(), MoveStatus.RENAME));
                            }
                            case SKIP -> {
                                long size = Files.isDirectory(src) ? 0 : Files.size(src);
                                results.add(new MoveResult(src, finalDest, size, java.time.Instant.now(), Files.isDirectory(src), MoveStatus.SKIPPED));
                            }
                            case CANCEL -> {
                                System.err.println("Operation cancelled by user.");
                                return 1;
                            }
                        }
                    } else {
                        results.add(mover.move(src, finalDest, options));
                    }
                }

                for (MoveResult res : results) {
                    printResult(res, options.verbose());
                }

                if (!options.dryRun()) {
                    List<OperationRecord> opRecords = new ArrayList<>();
                    String batchId = java.util.UUID.randomUUID().toString();
                    for (MoveResult res : results) {
                        if (res.status() == MoveStatus.MOVED || res.status() == MoveStatus.OVERWRITTEN || res.status() == MoveStatus.RENAME) {
                            opRecords.add(OperationRecord.create(
                                batchId,
                                OperationType.MOVE,
                                res.source().toString(),
                                res.destination().toString(),
                                res.trashUuid(),
                                res.sizeBytes(),
                                res.isDirectory()
                            ));
                        }
                    }
                    if (!opRecords.isEmpty()) {
                        try (HistoryDb db = new HistoryDb()) {
                            db.recordBatch(opRecords);
                        } catch (java.sql.SQLException e) {
                            System.err.println("Warning: Failed to record operation history: " + e.getMessage());
                        }
                    }
                }

                return 0;
            } catch (IOException e) {
                System.err.println("Error moving file/directory: " + e.getMessage());
                return 1;
            } catch (java.nio.file.InvalidPathException e) {
                System.err.println("Error: Invalid path: " + e.getInput());
                return 1;
            }
        }

        private void printResult(MoveResult result, boolean verbose) {
            String srcName = result.source().getFileName().toString();
            switch (result.status()) {
                case DRY_RUN -> System.out.printf("[DRY RUN] %s -> %s%n", result.source(), result.destination());
                case SKIPPED -> System.out.printf("[SKIPPED] %s already exists at %s%n", srcName, result.destination());
                case OVERWRITTEN -> {
                    if (verbose) {
                        System.out.printf("[OVERWRITTEN] %s -> %s%n", result.source(), result.destination());
                    } else {
                        System.out.printf("[OVERWRITTEN] %s%n", srcName);
                    }
                }
                case MOVED -> {
                    if (verbose) {
                        System.out.printf("[MOVED] %s -> %s%n", result.source(), result.destination());
                    } else {
                        System.out.printf("[MOVED] %s%n", srcName);
                    }
                }
                case RENAME -> {
                    if (verbose) {
                        System.out.printf("[RENAMED] %s -> %s%n", result.source(), result.destination());
                    } else {
                        System.out.printf("[RENAMED] %s -> %s%n", srcName, result.destination().getFileName());
                    }
                }
            }
        }

        private ConflictAction promptConflictAction(
            Path src,
            Path dest,
            BufferedReader in
        ) throws IOException {
            while (true) {
                System.out.println();
                System.out.printf("Conflict detected: %s already exists.%n", dest.getFileName());
                printFileInfo("Source:     ", src);
                printFileInfo("Destination:", dest);
                System.out.println();
                System.out.println("Choose an action:");
                System.out.println("[1] Overwrite");
                System.out.printf("[2] Rename (auto: %s)%n", mv.generateUniquePath(dest).getFileName());
                System.out.println("[3] Skip");
                System.out.println("[4] Compare");
                System.out.println("[5] Cancel");
                System.out.print("> ");
                System.out.flush();

                String line = in.readLine();
                if (line == null) {
                    return ConflictAction.CANCEL;
                }
                line = line.trim();
                switch (line) {
                    case "1", "o", "overwrite" -> { return ConflictAction.OVERWRITE; }
                    case "2", "r", "rename" -> { return ConflictAction.RENAME; }
                    case "3", "s", "skip" -> { return ConflictAction.SKIP; }
                    case "4", "c", "compare" -> {
                        System.out.println("----------------------------------------");
                        printFileInfo("Source:     ", src);
                        printFileInfo("Destination:", dest);
                        System.out.println("----------------------------------------");
                    }
                    case "5", "q", "cancel" -> { return ConflictAction.CANCEL; }
                    default -> System.out.println("Invalid choice: '" + line + "'. Please enter 1, 2, 3, 4, or 5.");
                }
            }
        }

        private void printFileInfo(String label, Path path) {
            try {
                long size = Files.isDirectory(path) ? 0 : Files.size(path);
                String time = Files.getLastModifiedTime(path).toInstant().toString().replace("T", " ").replace("Z", " ");
                System.out.printf("%-12s %s (Size: %,d bytes, Last Modified: %s)%n", label, path.toAbsolutePath(), size, time);
            } catch (IOException e) {
                System.out.printf("%-12s %s (Error retrieving size: %s)%n", label, path.toAbsolutePath(), e.getMessage());
            }
        }
    }

    @Command (name = "grep", aliases = {"g", "gr"}, description = "Searches for a specified pattern in files within a given directory.")
    static class GrepCommand implements Callable<Integer> {
        @Parameters (index = "0", description = "The search pattern (keyword).", defaultValue = "", arity = "0..1")
        private String pattern;

        @Parameters (index = "1", description = "The directory or file to search in.", defaultValue = "", arity = "0..1")
        private String targetInput;

        @Option (names = {"-s", "--case-sensitive"}, description = "Perform a case-sensitive search.", defaultValue = "false")
        private boolean caseSensitive;

        @Option (names = {"-r", "--regex"}, description = "Treat the query as a regular expression.", defaultValue = "false")
        private boolean regex;

        @Option (names = {"-e", "--ext"}, split = ",", description = "Filter results by file extensions (comma-separated or multiple flags).")
        private java.util.List<String> exts;

        @Option (names = {"-l", "-f", "--files-with-matches"}, description = "Only display files with matches, not the matching lines.", defaultValue = "false")
        private boolean filesWithMatches;

        @Option (names = {"-n", "--line-numbers"}, description = "Display line numbers for matching lines.", defaultValue = "false")
        private boolean lineNumbers;

        @Option (names = {"-x", "--exclude"}, split = ",", description = "Exclude directories by name (comma-separated or multiple flags).")
        private java.util.List<String> excludeDirs;

        @Option (names = {"-h", "-H", "--hidden"}, description = "Include hidden files and directories (default: excluded).", defaultValue = "false")
        private boolean hidden;

        @Option (names = {"--help"}, usageHelp = true, description = "Display this help message.")
        private boolean helpRequested;

        @Override 
        public Integer call() {
            if (helpRequested || pattern == null || pattern.isEmpty() || "?".equals(pattern) || "/?".equals(pattern) || "help".equalsIgnoreCase(pattern)) {
                CommandLine.usage(this, System.out);
                return 0;
            }

            GrepOptions options = new GrepOptions(caseSensitive, regex, normalizeExts(exts), filesWithMatches, lineNumbers, normalizeDirs(excludeDirs), hidden);
            gr grep = new gr();
            try {
                GrepResult result;
                boolean hasTarget = targetInput != null && !targetInput.isEmpty();
                if ("-".equals(targetInput) || (!hasTarget && hasPipedInput())) {
                    java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.InputStreamReader(System.in, java.nio.charset.StandardCharsets.UTF_8));
                    List<String> lines = reader.lines().toList();

                    boolean isFileList = !lines.isEmpty() && Files.exists(Path.of(lines.get(0)));
                    if (isFileList) {
                        List<Path> paths = lines.stream().map(Path::of).toList();
                        result = grep.grepFiles(paths, pattern, options);
                    } else {
                        String content = String.join(System.lineSeparator(), lines);
                        result = grep.grepStream(new java.io.BufferedReader(new java.io.StringReader(content)), pattern, options);
                    }
                } else {
                    Path root = hasTarget ? Path.of(targetInput) : Path.of(".");
                    if (!Files.exists(root)) {
                        System.err.println("Error: " + root + " does not exist.");
                        return 1;
                    }
                    result = grep.grep(root, pattern, options);
                }

                if (options.filesWithMatches()) {
                    for (Path path : result.matchingFiles()) {
                        System.out.println(path);
                    }
                } else {
                    for (GrepMatch match : result.matches()) {
                        if (match.file() != null) {
                            if (options.lineNumbers()) {
                                System.out.printf("%s:%d: %s%n", match.file(), match.lineNumber(), match.lineContent());
                            } else {
                                System.out.printf("%s: %s%n", match.file(), match.lineContent());
                            }
                        } else {
                            if (options.lineNumbers()) {
                                System.out.printf("%d: %s%n", match.lineNumber(), match.lineContent());
                            } else {
                                System.out.println(match.lineContent());
                            }
                        }
                    }
                }

                System.err.println();
                System.err.printf("Found %d matches in %d ms.%n", result.matchCount(), result.elapsedMillis());
                return 0;
            } catch (IOException e) {
                System.err.println("Error searching directory: "+ e.getMessage());
                return 1;
            }
        }
    }

    @Command(name = "rm", aliases = {"r", "del"}, mixinStandardHelpOptions = true,
             description = "Safely remove files or directories to trash (undoable).")
    static class RmCommand implements Callable<Integer> {

        @Parameters(arity = "0..*", description = "Target files or directories to remove")
        private List<String> targets;

        @Option(names = {"-r", "-R", "--recursive"}, description = "Remove directories and their contents recursively")
        private boolean recursive;

        @Option(names = {"-f", "--force"}, description = "Ignore non-existent files without error, or bypass confirmation on --purge")
        private boolean force;

        @Option(names = {"-v", "--verbose"}, description = "Verbose output displaying trash UUIDs and full paths")
        private boolean verbose;

        @Option(names = {"--purge", "--empty-trash"}, description = "Permanently empty items from trash vault (irreversible)")
        private boolean purge;

        @Option(names = {"--days"}, description = "Only purge trash items older than specified number of days (used with --purge)")
        private Integer days;

        @Override
        public Integer call() {
            if (purge) {
                return PurgeCommand.executePurge(force, days);
            }

            if (targets == null || targets.isEmpty()) {
                System.err.println("Error: No target specified to remove.");
                return 1;
            }

            if (targets.size() == 1) {
                String single = targets.get(0);
                if ("?".equals(single) || "/?".equals(single) || "-?".equals(single) || "help".equalsIgnoreCase(single)) {
                    CommandLine.usage(this, System.out);
                    return 0;
                }
            }

            List<Path> paths = new ArrayList<>();
            for (String t : targets) {
                Path p = Path.of(t);
                if (!Files.exists(p)) {
                    if (force) {
                        continue;
                    } else {
                        System.err.println("Error: File or directory not found: " + t);
                        return 1;
                    }
                }
                paths.add(p);
            }

            if (paths.isEmpty()) {
                return 0;
            }

            try (HistoryDb db = new HistoryDb()) {
                TrashVault vault = new TrashVault();
                rm remover = new rm(vault, db);

                List<RemoveResult> results = remover.removeAll(paths, recursive);
                for (RemoveResult res : results) {
                    if (verbose) {
                        System.out.printf("[REMOVED] %s (UUID: %s, %s bytes)%n",
                            res.path(), res.trashUuid(), res.isDirectory() ? "dir" : String.format("%,d", res.sizeByte()));
                    } else {
                        System.out.printf("[REMOVED] %s%n", res.path().getFileName());
                    }
                }
                return 0;
            } catch (java.nio.file.NoSuchFileException e) {
                if (!force) {
                    System.err.println("Error: File or directory not found: " + e.getMessage());
                    return 1;
                }
                return 0;
            } catch (IOException e) {
                System.err.println("Error removing target: " + e.getMessage());
                return 1;
            } catch (java.sql.SQLException e) {
                System.err.println("Database error recording removal: " + e.getMessage());
                return 1;
            }
        }
    }

    @Command(name = "purge", aliases = {"clean", "empty-trash"}, mixinStandardHelpOptions = true,
             description = "Permanently delete items from the trash vault (irreversible).")
    static class PurgeCommand implements Callable<Integer> {

        @Option(names = {"-y", "--yes"}, description = "Bypass confirmation prompt")
        private boolean yes;

        @Option(names = {"-f", "--force"}, description = "Bypass confirmation prompt (alias for -y)")
        private boolean force;

        @Option(names = {"--days"}, description = "Only purge trash items older than specified number of days")
        private Integer days;

        @Parameters(arity = "0..*", description = "Optional arguments or '?' for help", hidden = true)
        private List<String> targets;

        @Override
        public Integer call() {
            if (targets != null && targets.size() == 1) {
                String single = targets.get(0);
                if ("?".equals(single) || "/?".equals(single) || "-?".equals(single) || "help".equalsIgnoreCase(single)) {
                    CommandLine.usage(this, System.out);
                    return 0;
                }
            }
            return executePurge(yes || force, days);
        }

        public static int executePurge(boolean forceOrYes, Integer days) {
            if (!forceOrYes) {
                System.out.println("WARNING: This operation permanently deletes items from the trash vault and cannot be undone!");
                System.out.print("Are you sure you want to proceed? [y/N]: ");
                System.out.flush();
                try {
                    BufferedReader reader = new BufferedReader(new java.io.InputStreamReader(System.in, java.nio.charset.StandardCharsets.UTF_8));
                    String answer = reader.readLine();
                    if (answer == null || (!answer.trim().equalsIgnoreCase("y") && !answer.trim().equalsIgnoreCase("yes"))) {
                        System.out.println("Purge cancelled.");
                        return 0;
                    }
                } catch (IOException e) {
                    System.err.println("Error reading confirmation: " + e.getMessage());
                    return 1;
                }
            }

            try (HistoryDb db = new HistoryDb()) {
                TrashVault vault = new TrashVault();
                int count;
                if (days != null && days > 0) {
                    count = vault.purgeExpired(java.time.Duration.ofDays(days), db);
                    if (count == 0) {
                        System.out.printf("No trash items older than %d day(s) found.%n", days);
                    } else {
                        System.out.printf("Permanently purged %d item(s) older than %d day(s) from trash.%n", count, days);
                    }
                } else {
                    count = vault.purgeAll(db);
                    if (count == 0) {
                        System.out.println("Trash is already empty. 0 items purged.");
                    } else {
                        System.out.printf("Permanently purged %d item(s) from trash.%n", count);
                    }
                }
                return 0;
            } catch (Exception e) {
                System.err.println("Error purging trash: " + e.getMessage());
                return 1;
            }
        }
    }

    @Command(name = "log", aliases = {"l", "history"}, mixinStandardHelpOptions = true,
             description = "Show recent operation history or export to JSON.")
    static class LogCommand implements Callable<Integer> {

        @Option(names = {"-n", "--limit"}, defaultValue = "10", description = "Number of recent operations to show (default: 10)")
        private int limit;

        @Option(names = {"-o", "--output"}, description = "Export history to a JSON file (e.g. -o log -> log.json)")
        private String output;

        @Option(names = {"-v", "--verbose"}, description = "Display full paths and extra details")
        private boolean verbose;

        @Parameters(arity = "0..1", description = "Optional argument or '?' for help")
        private String query;

        @Override
        public Integer call() {
            if ("?".equals(query) || "/?".equals(query) || "help".equalsIgnoreCase(query)) {
                CommandLine.usage(this, System.out);
                return 0;
            }

            try (HistoryDb db = new HistoryDb()) {
                List<OperationRecord> records = db.findRecent(limit);
                if (records.isEmpty()) {
                    System.out.println("No operation history found.");
                    return 0;
                }

                if (output != null && !output.isBlank()) {
                    String fileName = output.endsWith(".json") ? output : output + ".json";
                    Path outPath = Path.of(fileName);
                    String json = formatAsJson(records);
                    Files.writeString(outPath, json, java.nio.charset.StandardCharsets.UTF_8);
                    System.out.printf("Exported %d records to %s%n", records.size(), outPath.toAbsolutePath());
                    return 0;
                }

                printTable(records, verbose);
                return 0;
            } catch (Exception e) {
                System.err.println("Error reading operation history: " + e.getMessage());
                return 1;
            }
        }

        private void printTable(List<OperationRecord> records, boolean verbose) {
            System.out.printf("%-5s %-20s %-8s %-10s %s%n", "ID", "TIMESTAMP", "TYPE", "STATUS", "DETAILS");
            System.out.println("-".repeat(80));
            for (OperationRecord rec : records) {
                String rawTime = rec.timestamp().toString().replace("T", " ");
                String timeStr = rawTime.length() >= 19 ? rawTime.substring(0, 19) : rawTime;
                String details;
                if (rec.operationType() == OperationType.REMOVE) {
                    String pathStr = verbose ? rec.sourcePath() : Path.of(rec.sourcePath()).getFileName().toString();
                    details = pathStr + (rec.trashUuid() != null ? " (UUID: " + rec.trashUuid() + ")" : "");
                } else {
                    String srcStr = verbose ? rec.sourcePath() : Path.of(rec.sourcePath()).getFileName().toString();
                    String destStr = rec.destinationPath() != null
                        ? (verbose ? rec.destinationPath() : Path.of(rec.destinationPath()).getFileName().toString())
                        : "-";
                    details = srcStr + " -> " + destStr + (rec.trashUuid() != null ? " [OVERWRITTEN]" : "");
                }
                System.out.printf("%-5d %-20s %-8s %-10s %s%n",
                    rec.id(), timeStr, rec.operationType(), rec.status(), details);
            }
            System.out.println("-".repeat(80));
            System.out.printf("Showing %d recent operations.%n", records.size());
        }

        private String formatAsJson(List<OperationRecord> records) {
            StringBuilder sb = new StringBuilder();
            sb.append("[\n");
            for (int i = 0; i < records.size(); i++) {
                OperationRecord r = records.get(i);
                sb.append("  {\n");
                sb.append("    \"id\": ").append(r.id()).append(",\n");
                sb.append("    \"batchId\": ").append(escapeJson(r.batchID())).append(",\n");
                sb.append("    \"operationType\": ").append(escapeJson(r.operationType().name())).append(",\n");
                sb.append("    \"sourcePath\": ").append(escapeJson(r.sourcePath())).append(",\n");
                sb.append("    \"destinationPath\": ").append(r.destinationPath() != null ? escapeJson(r.destinationPath()) : "null").append(",\n");
                sb.append("    \"trashUuid\": ").append(r.trashUuid() != null ? escapeJson(r.trashUuid()) : "null").append(",\n");
                sb.append("    \"fileSize\": ").append(r.fileSize()).append(",\n");
                sb.append("    \"isDirectory\": ").append(r.isDirectory()).append(",\n");
                sb.append("    \"status\": ").append(escapeJson(r.status().name())).append(",\n");
                sb.append("    \"timestamp\": ").append(escapeJson(r.timestamp().toString())).append("\n");
                sb.append("  }");
                if (i < records.size() - 1) {
                    sb.append(",");
                }
                sb.append("\n");
            }
            sb.append("]\n");
            return sb.toString();
        }

        private static String escapeJson(String s) {
            if (s == null) return "null";
            return "\"" + s.replace("\\", "\\\\")
                           .replace("\"", "\\\"")
                           .replace("\b", "\\b")
                           .replace("\f", "\\f")
                           .replace("\n", "\\n")
                           .replace("\r", "\\r")
                           .replace("\t", "\\t") + "\"";
        }
    }

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }
}
